/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSocialRouteImport } from './routes/_app.social'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppGovernanceRouteImport } from './routes/_app.governance'
import { Route as AppEnvironmentalRouteImport } from './routes/_app.environmental'
import { Route as AppEmployeesRouteImport } from './routes/_app.employees'
import { Route as AppDepartmentsRouteImport } from './routes/_app.departments'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSocialRoute = AppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGovernanceRoute = AppGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AppRoute,
} as any)
const AppEnvironmentalRoute = AppEnvironmentalRouteImport.update({
  id: '/environmental',
  path: '/environmental',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/departments': typeof AppDepartmentsRoute
  '/employees': typeof AppEmployeesRoute
  '/environmental': typeof AppEnvironmentalRoute
  '/governance': typeof AppGovernanceRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/social': typeof AppSocialRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/departments': typeof AppDepartmentsRoute
  '/employees': typeof AppEmployeesRoute
  '/environmental': typeof AppEnvironmentalRoute
  '/governance': typeof AppGovernanceRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/social': typeof AppSocialRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/environmental': typeof AppEnvironmentalRoute
  '/_app/governance': typeof AppGovernanceRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/social': typeof AppSocialRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/departments'
    | '/employees'
    | '/environmental'
    | '/governance'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/social'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/departments'
    | '/employees'
    | '/environmental'
    | '/governance'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/social'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/departments'
    | '/_app/employees'
    | '/_app/environmental'
    | '/_app/governance'
    | '/_app/leaderboard'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/social'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/social': {
      id: '/_app/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AppSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/governance': {
      id: '/_app/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AppGovernanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/environmental': {
      id: '/_app/environmental'
      path: '/environmental'
      fullPath: '/environmental'
      preLoaderRoute: typeof AppEnvironmentalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppEnvironmentalRoute: typeof AppEnvironmentalRoute
  AppGovernanceRoute: typeof AppGovernanceRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSocialRoute: typeof AppSocialRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppEnvironmentalRoute: AppEnvironmentalRoute,
  AppGovernanceRoute: AppGovernanceRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSocialRoute: AppSocialRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
